[openctireporthits]
filename = openctireporthits.py
chunked = true
python.version = python3

[openctivalidation]
filename = openctivalidation.py
chunked = true
python.version = python3

[openctireconcile]
filename = openctireconcile.py
chunked = true
python.version = python3

[openctiprovides]
filename = openctiprovides.py
chunked = true
python.version = python3
