[openctireporthits]
filename = openctireporthits.py
chunked = true
python.version = python3
python.required = 3.13

[openctivalidation]
filename = openctivalidation.py
chunked = true
python.version = python3
python.required = 3.13

[openctireconcile]
filename = openctireconcile.py
chunked = true
python.version = python3
python.required = 3.13

[openctiprovides]
filename = openctiprovides.py
chunked = true
python.version = python3
python.required = 3.13
