"""Test doubles shared by the program compatibility tests (OpenCTI-Platform/splunk-enterprise-add-on#68)."""
import os
import re
import sys
import types

APP_BIN = os.path.join(os.path.dirname(__file__), "..", "TA-opencti-for-splunk-enterprise", "package", "bin")
sys.path.insert(0, os.path.abspath(APP_BIN))

# import_declare_test is generated by UCC to put lib/ on sys.path.
sys.modules.setdefault("import_declare_test", types.ModuleType("import_declare_test"))

from app_connector_helper import OpenCTIGraphQLError  # noqa: E402
from opencti_features import OpenCTIFeatureDetector  # noqa: E402

_OPERATION_RE = re.compile(r"(?:query|mutation)\s+(\w+)")


class FakeClient:
    """SplunkAppConnectorHelper double: routes GraphQL operations to handlers by operation name."""

    def __init__(self, handlers=None, opencti_url="https://opencti.example"):
        self.handlers = dict(handlers or {})
        self.opencti_url = opencti_url
        self.calls = []
        self.bundles = []
        self.registered = 0

    def graphql_query(self, query, variables=None):
        match = _OPERATION_RE.search(query)
        name = match.group(1) if match else ""
        self.calls.append((name, variables or {}))
        handler = self.handlers.get(name)
        if handler is None:
            raise AssertionError(f"Unexpected GraphQL operation {name}")
        result = handler(variables or {}) if callable(handler) else handler
        if isinstance(result, Exception):
            raise result
        return result

    def calls_of(self, name):
        return [variables for operation, variables in self.calls if operation == name]

    def register(self):
        self.registered += 1

    def send_stix_bundle(self, bundle):
        self.bundles.append(bundle)
        return "ok"


class FakeDetector:
    def __init__(self, features=(), failed=False):
        self.features = set(features)
        self.failed = failed
        self.required = []

    def snapshot(self, refresh=False):
        return {"features": sorted(self.features), "version": "test", "failed": self.failed}

    @property
    def version(self):
        return "test"

    def has(self, feature):
        return feature in self.features

    def require(self, feature, action):
        self.required.append((feature, action))
        return feature in self.features


class FakeKV:
    """KVCollection double."""

    def __init__(self, records=None):
        self.records = {}
        for record in records or []:
            self.records[record["_key"]] = dict(record)
        self.saved = []

    def get(self, key):
        record = self.records.get(key)
        return dict(record) if record else None

    def upsert(self, records):
        for record in records:
            self.records[record["_key"]] = dict(record)
            self.saved.append(dict(record))
        return len(records)

    def query(self, query=None, limit=0, skip=0, fields=None, sort=None):
        rows = [dict(r) for _, r in sorted(self.records.items()) if self._matches(r, query or {})]
        rows = rows[skip:]
        return rows[:limit] if limit else rows

    @staticmethod
    def _matches(record, query):
        if "$or" in query:
            return any(FakeKV._matches(record, branch) for branch in query["$or"])
        return all(record.get(k) == v for k, v in query.items())

    def get_many(self, keys):
        return {key: dict(self.records[key]) for key in keys if key in self.records}

    truncated = False

    def query_all(self, query=None, page_size=1000, fields=None, max_records=1000000):
        rows = self.query(query=query)
        self.truncated = len(rows) > max_records
        for row in rows[:max_records]:
            yield row


class FakeCache:
    """KVStoreCache double."""

    persistent = True

    def __init__(self):
        self.values = {}

    def get(self, key):
        return self.values.get(key)

    def set(self, key, value):
        self.values[key] = value

    def reserve(self, key, value):
        if key in self.values:
            return False
        self.values[key] = value
        return True

    def release(self, key):
        self.values.pop(key, None)

    def items(self, prefix, limit=100):
        return [(key, value) for key, value in self.values.items() if key.startswith(prefix) and value][:limit]


class FakeLogger:
    def __init__(self):
        self.lines = []

    def _log(self, level, message):
        self.lines.append((level, str(message)))

    def debug(self, message):
        self._log("debug", message)

    def info(self, message):
        self._log("info", message)

    def warning(self, message):
        self._log("warning", message)

    warn = warning

    def error(self, message):
        self._log("error", message)

    def has(self, level, fragment):
        return any(lvl == level and fragment in line for lvl, line in self.lines)


def graphql_error(message):
    return OpenCTIGraphQLError(f"OpenCTI GraphQL errors: {message}", errors=[{"message": message}], status_code=200)


def transport_error(message="connection refused"):
    return OpenCTIGraphQLError(f"OpenCTI GraphQL request failed: {message}")


__all__ = [
    "APP_BIN",
    "FakeCache",
    "FakeClient",
    "FakeDetector",
    "FakeKV",
    "FakeLogger",
    "OpenCTIFeatureDetector",
    "graphql_error",
    "transport_error",
]
