"""Test doubles shared by the program compatibility tests (OpenCTI-Platform/splunk-enterprise-add-on#68)."""
import os
import re
import sys
import types

APP_BIN = os.path.join(os.path.dirname(__file__), "..", "TA-opencti-for-splunk-enterprise", "package", "bin")
sys.path.insert(0, os.path.abspath(APP_BIN))

# Modules that need a running Splunk: splunktaucclib's alert base imports
# splunkd internals (the helpers only use ModularAlertBase as a type hint),
# and import_declare_test is generated by UCC to put lib/ on sys.path.
try:
    import splunktaucclib.alert_actions_base  # type: ignore  # noqa: F401
except ImportError:
    _alert_base = types.ModuleType("splunktaucclib.alert_actions_base")
    _alert_base.ModularAlertBase = object
    sys.modules["splunktaucclib.alert_actions_base"] = _alert_base
sys.modules.setdefault("import_declare_test", types.ModuleType("import_declare_test"))

from app_connector_helper import OpenCTIGraphQLError  # noqa: E402
from opencti_features import OpenCTIFeatureDetector  # noqa: E402

_OPERATION_RE = re.compile(r"(?:query|mutation)\s+(\w+)")


class FakeClient:
    """SplunkAppConnectorHelper double: routes GraphQL operations to handlers by operation name."""

    def __init__(self, handlers=None, opencti_url="https://opencti.example"):
        self.handlers = dict(handlers or {})
        self.opencti_url = opencti_url
        self.calls = []
        self.bundles = []
        self.registered = 0

    def graphql_query(self, query, variables=None):
        match = _OPERATION_RE.search(query)
        name = match.group(1) if match else ""
        self.calls.append((name, variables or {}))
        handler = self.handlers.get(name)
        if handler is None:
            raise AssertionError(f"Unexpected GraphQL operation {name}")
        result = handler(variables or {}) if callable(handler) else handler
        if isinstance(result, Exception):
            raise result
        return result

    def calls_of(self, name):
        return [variables for operation, variables in self.calls if operation == name]

    def register(self):
        self.registered += 1

    def send_stix_bundle(self, bundle):
        self.bundles.append(bundle)
        return "ok"


class FakeDetector:
    def __init__(self, features=(), failed=False):
        self.features = set(features)
        self.failed = failed
        self.required = []

    def snapshot(self, refresh=False):
        return {"features": sorted(self.features), "version": "test", "failed": self.failed}

    @property
    def version(self):
        return "test"

    def has(self, feature):
        return feature in self.features

    def require(self, feature, action):
        self.required.append((feature, action))
        return feature in self.features


class FakeKV:
    """KVCollection double."""

    def __init__(self, records=None):
        self.records = {}
        for record in records or []:
            self.records[record["_key"]] = dict(record)
        self.saved = []

    def get(self, key):
        record = self.records.get(key)
        return dict(record) if record else None

    def upsert(self, records):
        for record in records:
            self.records[record["_key"]] = dict(record)
            self.saved.append(dict(record))
        return len(records)

    def query(self, query=None, limit=0, skip=0, fields=None, sort=None):
        rows = [dict(r) for _, r in sorted(self.records.items()) if self._matches(r, query or {})]
        rows = rows[skip:]
        return rows[:limit] if limit else rows

    @staticmethod
    def _matches(record, query):
        if "$or" in query:
            return any(FakeKV._matches(record, branch) for branch in query["$or"])
        return all(record.get(k) == v for k, v in query.items())

    def get_many(self, keys):
        return {key: dict(self.records[key]) for key in keys if key in self.records}

    def query_all(self, query=None, page_size=1000, fields=None, max_records=1000000, sort="_key"):
        for row in self.query(query=query):
            yield row


class FakeCache:
    def __init__(self):
        self.values = {}

    def get(self, key):
        return self.values.get(key)

    def set(self, key, value):
        self.values[key] = value


class FakeLogger:
    def __init__(self):
        self.lines = []

    def _log(self, level, message):
        self.lines.append((level, str(message)))

    def debug(self, message):
        self._log("debug", message)

    def info(self, message):
        self._log("info", message)

    def warning(self, message):
        self._log("warning", message)

    warn = warning

    def error(self, message):
        self._log("error", message)

    def has(self, level, fragment):
        return any(lvl == level and fragment in line for lvl, line in self.lines)


class FakeAlertHelper:
    """splunktaucclib ModularAlertBase double."""

    def __init__(self, params=None, events=None, settings=None, global_settings=None):
        self.params = dict(params or {})
        self.events = list(events or [])
        self.settings = dict(settings or {"search_name": "Brute force", "results_link": "https://splunk/results"})
        self.search_name = self.settings.get("search_name")
        self.global_settings = dict(global_settings or {
            "opencti_url": "https://opencti.example",
            "opencti_api_key": "key",
        })
        self.session_key = "session"
        self.log_level = "INFO"
        self.logs = []

    def get_param(self, name):
        return self.params.get(name)

    def get_global_setting(self, name):
        return self.global_settings.get(name)

    def get_proxy(self):
        return {}

    def get_events(self):
        return iter(self.events)

    def set_log_level(self, level):
        pass

    def log_error(self, message):
        self.logs.append(("error", message))

    def log_info(self, message):
        self.logs.append(("info", message))

    def log_debug(self, message):
        self.logs.append(("debug", message))

    def log_warn(self, message):
        self.logs.append(("warning", message))

    def errors(self):
        return [message for level, message in self.logs if level == "error"]


class FakeAlertContext:
    """alert_common.AlertContext double built on the fakes above."""

    def __init__(self, helper, client=None, detector=None, platform=None, service=None):
        from alert_common import AlertContext

        self.helper = helper
        self.logger = FakeLogger()
        self.client = client or FakeClient()
        self.detector = detector or FakeDetector()
        self._platform = platform
        self.cache = FakeCache()
        self.service = service
        self.followups = []
        self.container_ids = {}
        self._real = AlertContext

    @property
    def platform(self):
        return self._platform

    @property
    def search_name(self):
        return self.helper.search_name

    @property
    def results_link(self):
        return self.helper.settings.get("results_link", "")

    def param(self, name, default=None):
        value = self.helper.get_param(name)
        return default if value is None else value

    def flag(self, name, default=False):
        from addon_config import is_true

        return is_true(self.helper.get_param(name), default)

    def defer(self, entity_id, description, action):
        self.followups.append((entity_id, description, action))

    def run_followups(self, sleep=None, budget=0):
        pending, self.followups = self.followups, []
        for _, _, action in pending:
            action()
        return 0


def graphql_error(message):
    return OpenCTIGraphQLError(f"OpenCTI GraphQL errors: {message}", errors=[{"message": message}], status_code=200)


def transport_error(message="connection refused"):
    return OpenCTIGraphQLError(f"OpenCTI GraphQL request failed: {message}")


__all__ = [
    "APP_BIN",
    "FakeAlertContext",
    "FakeAlertHelper",
    "FakeCache",
    "FakeClient",
    "FakeDetector",
    "FakeKV",
    "FakeLogger",
    "OpenCTIFeatureDetector",
    "graphql_error",
    "transport_error",
]
